### ISSUE TITLE
Does not compile on C++11

### ISSUE THREAD

**Issue by kanazir** [dabbertorres/ThreadPool#1]
ThreadPool.cpp: In member function ‘dbr::cc::ThreadPool::Ids dbr::cc::ThreadPool::ids() const’:
ThreadPool.cpp:51:67: error: use of ‘auto’ in lambda parameter declaration only available with -std=c++14 or -std=gnu++14

Tested on gcc 5.4.0.

**Comment by dabbertorres** [comment]
Thanks for reporting! Should be fixed now.

**Comment by kanazir** [comment]
Works perfectly :)
