### ISSUE TITLE
Standard Library Header Inclusion Missing

### ISSUE THREAD

**Issue by ghost** [dabbertorres/ThreadPool#2]
In ThreadPool.cpp, the inclusion of std library header "algorithm" is missing:

`#include <algorithm>`

The inclusion of this header is needed because of `std::transform` and `std::generate_n` used in the CPP file.

**Comment by dabbertorres** [comment]
That is a very good point. I guess the standard libraries I've used #include <algorithm> in one of the headers I'm including already, and I missed it.

Regardless, thanks for the report! Feel free to make a PR, otherwise I'll push a fix later today.
